### ISSUE TITLE
Exception: No such prekeyRecord!

### ISSUE THREAD

**Issue by kndone** [shaleenx/Raspberry-Pi-Chatbot#1]
Hi, I tried to run the script, I got it running, but after sending the Song command, I got an error "Exception: No such prekeyRecord!", I restarted the Raspberry, installed Yowsup again, but the error persist everytime I run ./whatsapp or python run.py. I hope anyone could help me, thanks.
Here is the error I got:

root@jarvian:/home/pi/apps/chatbot/yowsup_python# python run.py
No handlers could be found for logger "yowsup.stacks.yowstack"
Traceback (most recent call last):
File "run.py", line 39, in 
stack.loop()
File "build/bdist.linux-armv7l/egg/yowsup/stacks/yowstack.py", line 195, in loop
File "/usr/lib/python2.7/asyncore.py", line 216, in loop
poll_fun(timeout, map)
File "/usr/lib/python2.7/asyncore.py", line 156, in poll
read(obj)
File "/usr/lib/python2.7/asyncore.py", line 87, in read
obj.handle_error()
File "/usr/lib/python2.7/asyncore.py", line 83, in read
obj.handle_read_event()
File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
self.handle_read()
File "build/bdist.linux-armv7l/egg/yowsup/layers/network/layer.py", line 86, in handle_read
self.toLower(receipt)
File "build/bdist.linux-armv7l/egg/yowsup/layers/network/layer.py", line 94, in receive
"Usage: \nweather {city_name}",
File "build/bdist.linux-armv7l/egg/yowsup/layers/init.py", line 59, in toUpper
File "build/bdist.linux-armv7l/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
class EchoLayer(YowInterfaceLayer):
File "build/bdist.linux-armv7l/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
r = song.download(t1,'3gp','./videosongs/')
File "build/bdist.linux-armv7l/egg/yowsup/layers/init.py", line 59, in toUpper
File "build/bdist.linux-armv7l/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
File "build/bdist.linux-armv7l/egg/yowsup/layers/init.py", line 59, in toUpper
File "build/bdist.linux-armv7l/egg/yowsup/layers/coder/layer.py", line 35, in receive
if True:
File "build/bdist.linux-armv7l/egg/yowsup/layers/init.py", line 59, in toUpper
File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer.py", line 117, in receive
self.toLower(receipt)
File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer.py", line 139, in onMessage

File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer.py", line 222, in handleEncMessage

File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/layer.py", line 259, in handlePreKeyWhisperMessage

File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessioncipher.py", line 91, in decryptPkmsg
File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessionbuilder.py", line 43, in process
File "/usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.7-py2.7.egg/axolotl/sessionbuilder.py", line 113, in processV3
File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/store/sqlite/liteaxolotlstore.py", line 32, in loadPreKey
File "build/bdist.linux-armv7l/egg/yowsup/layers/axolotl/store/sqlite/liteprekeystore.py", line 20, in loadPreKey
Exception: No such prekeyRecord!

**Comment by kndone** [comment]
I got it working again by re-installing Python.

**Comment by shaleenx** [comment]
@kndone Glad that you were able to find your way. Sorry I could not respond in time.
The project has been built over Python v2.7 and Yowsup cli 2.0.
